version: '3'
services:
  backend:
    build:
      context: './backend'
    ports:
      - 127.0.0.1:5501:8888
    restart: always
    volumes:
      - ./backend:/app
      - cache:/app/.cache/
      - data:/app/data/
    environment:
      - FLASK_ENV=development
    env_file:
      - ./backend/.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["1"]
              capabilities: [ gpu ]
  frontend:
    build:
      context: './frontend'
    ports:
      - 127.0.0.1:5502:80
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    depends_on:
      - backend
    restart: always
volumes:
  node_modules:
  cache:
  data: