version: '3'
services:
  backend:
    build:
      context: './backend'
    ports:
      - 127.0.0.1:5501:8888
    restart: always
    volumes:
      - ./backend:/app
      - cache:/app/.cache/
      - data:/app/data/
    environment:
      - FLASK_ENV=development
    env_file:
      - ./backend/.env
  frontend:
    build:
      context: './frontend'
    ports:
      - 127.0.0.1:5502:80
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    depends_on:
      - backend
    restart: always
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  worker:
    build: 
      context: ./backend
    command: celery -A celery_app worker --pool=solo --loglevel=info
    volumes:
      - ./backend:/app
      - cache:/app/.cache/
      - data:/app/data/
      - celery_data:/data
    env_file:
      - ./backend/.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    links:
      - redis
    depends_on:
      - redis
      - backend
volumes:
  node_modules:
  cache:
  data:
  celery_data: